### ISSUE TITLE
npm install warning

### ISSUE THREAD

**Issue by yyynnn** [simonepri/env-dot-prop#3]
`env-dot-prop > circular-json@0.4.0: CircularJSON is in maintenance only, flatted is its successor.`

could be updated

**Comment by simonepri** [comment]
Hi @yyynnn, I've updated CircularJSON to the last version 0.5.9, and I have released a new version of this package.

The warning is still there because I didn't used flatted.
The flatted's API is completely different, and I don't have time right now to dive into it.
Could you try to submit a PR for it?

**Comment by lorenzorapetti** [comment]
I've been playing around with flatted. The API is not backwards compatible, so you might have to bump the library to `2.0`.

I've made a branch in my fork [here](https://github.com/loryman/env-dot-prop/tree/circular-json-to-flatted). All the tests are passing except for the one with the circular dependency.

If you want i can create a pr with the major version bump :)

**Comment by simonepri** [comment]
> "If you want i can create a pr with the major version bump :)"

Yes please.

> "All the tests are passing except for the one with the circular dependency."

Because the encoding for the circular dependency is different with flatted right?
Can we fix it?

**Comment by lorenzorapetti** [comment]
I created pr #4 

To my understanding flatted works with arrays, so something like:

```js
const a = {};
a.a = a;
```

would became `[{"a":"0"}]` where `"0"` is the index where the circular dependency is.

I've tried to make it backwards compatible but i think it's too much work. We're better off with bumping to 2.0 or stick with the warning imo.

**Comment by simonepri** [comment]
@yyynnn The warning should be gone in `v2.0.0`
More details [here](https://github.com/simonepri/env-dot-prop/pull/4#issuecomment-449733381).
